# Generated by Django 3.2.6 on 2021-08-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add',
        ),
    ]
